aubo_i5:
  #home configuration, the robot end effector pose when all joints are zeros
  #general format [x,y,z,x,y,z,w】
  #the first three numbers are position, the last four numbers are unit quaternion
  home_configuration: [0.0,-0.2155,1.0085,0.70710678,0.0,-0.0,0.70710678]

  #is the screw axes presented in body frame
  isInBodyFrame: false

  #screw axes
  #general format S1 = [W;V] col vector
  screw_axes:
    S1: [0,0,1,0,0,0]
    S2: [0,-1,0,0,0.122,0]
    S3: [0,1,0,-0.53,0,0]
    S4: [0,-1,0,0.906,0,0]
    S5: [0,0,1,-0.1215,0,0]
    S6: [0,-1,0,1.0085,0,0]